spring:
  application:
    name: consul-example
  cloud:
    config:
      enabled: false
    consul:
      enabled: true
      host: 127.0.0.1
      port: 8500
      discovery:
        tags: management.context-path=/, health.path=/health


management.context-path: /
endpoints.health.path: /health

spring.boot.admin.discovery:
  ignored-services: consul
server:
  port: 8081
